### PR TITLE
Return errors for additional properties.

### PR DESCRIPTION
**Pull request by michaelrhodes**
Sorry, I messed this up…

### CODE REVIEW

**Comment by gummesson** [comment]
Is there any reason why you'd close this? I was just about to merge it. :)

**Comment by michaelrhodes** [comment]
Oh, how embarrasing. So I made a logic mistake (there’s no reason to compare the number of keys in each object) and then made more mistakes (rebasing a branch I had already pushed) trying to cover it up! :p

**Comment by gummesson** [comment]
Aha, okay. Yeah, now I see it. I merged the other one instead. :)

**Comment by michaelrhodes** [comment]
Hehe, thanks! :)

**Pull request closed without merging**
